sonar.projectKey=fitforge-user-service
sonar.projectName=fitforge-user-service

# Point to the root directory so paths in lcov.info (like src/app.js) match correctly
sonar.sources=.
sonar.inclusions=src/**/*.js
sonar.exclusions=src/**/*.test.js, **/node_modules/**, coverage/**

sonar.tests=src
sonar.test.inclusions=src/**/*.test.js

# Coverage report path
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.sourceEncoding=UTF-8
