sonar.projectKey=fitforge-user-service
sonar.projectName=fitforge-user-service

sonar.sources=.
sonar.inclusions=src/**/*.js
sonar.exclusions=**/node_modules/**, coverage/**

sonar.coverage.exclusions=**

sonar.sourceEncoding=UTF-8