name: CI — User Service

on:
  push:
    branches: 
      - develop
      - main
    paths:
      - "services/user-service/**"
      - ".github/workflows/ci-user-service.yml"
      - ".github/workflows/_ci-template.yml"
  pull_request:
    branches:
      - develop
      - main
    paths:
      - "services/user-service/**"
      - ".github/workflows/ci-user-service.yml"
      - ".github/workflows/_ci-template.yml"

# give the workflow permission to write to the repository contents
permissions:
  contents: write


jobs:
  ci:
    uses: ./.github/workflows/_ci-template.yml
    with:
      service-name: user-service
      service-path: services/user-service
      runtime: node
      node-version: "20"
      environment: ${{ github.ref_name }}
    secrets: inherit